---
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my-0.cnf: |
    [mysqld]
    server-id=1                
    log_bin=mysql-bin          
    binlog_format=ROW          
    gtid_mode=ON               
    enforce_gtid_consistency=ON
    master_info_repository=TABLE
    relay_log_info_repository=TABLE
    sync_binlog=1
    relay_log_recovery=ON
  my-1.cnf: |
    [mysqld]
    server-id=2
    log_bin=mysql-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce_gtid_consistency=ON
    master_info_repository=TABLE
    relay_log_info_repository=TABLE
    sync_binlog=1
    relay_log_recovery=ON
  my-2.cnf: |
    [mysqld]
    server-id=3
    log_bin=mysql-bin
    binlog_format=ROW
    gtid_mode=ON
    enforce_gtid_consistency=ON
    master_info_repository=TABLE
    relay_log_info_repository=TABLE
    sync_binlog=1
    relay_log_recovery=ON



