---
#
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx-deployment
  ports:
    - name: http-server
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  