---
#
apiVersion: v1
kind: Service
metadata:
  name: my-ExternalIps
spec:
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  externalIPs:
    - 80.11.12.10
  