---
# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev-team
  name: dev-role-binding
subjects:
  - kind: User
    name: developer-user       # Имя пользователя, которому предоставляем доступ
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role           # Привязываем к Role
  name: dev-role       # Название Role
  apiGroup: rbac.authorization.k8s.io

