---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80 default_server;
        server_name  _;

        default_type text/plain;

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
            autoindex on; # Эта строка разрешает автоиндексацию, если index.html отсутствует
        }
    }
