apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
        - name: nginx-deployment
          image: nginx:1.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: local-storage
            - name: config
              mountPath: /etc/nginx/conf.d

          readinessProbe:
            failureThreshold: 1
            periodSeconds: 10
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            timeoutSeconds: 1

          livenessProbe:
            failureThreshold: 1
            periodSeconds: 10
            httpGet:
              path: /
              port: 80
            successThreshold: 1
            timeoutSeconds: 15
            initialDelaySeconds: 45

          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 1Gi
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-pvc
        - name: config
          configMap:
            name: nginx-config
      restartPolicy: Always
      